# Generated by Django 5.0.7 on 2024-07-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0002_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='Немає відповіді', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chemistry.grade'),
        ),
    ]
