# Generated by Django 5.0.7 on 2024-07-24 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0003_alter_question_answer_alter_question_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='chemistry.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='chemistry.grade'),
        ),
        migrations.AlterField(
            model_name='question',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
