# Generated by Django 5.1.1 on 2024-09-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0004_alter_question_category_alter_question_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category_def',
            field=models.TextField(default='0'),
        ),
    ]
